---
version: "3.8"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=hello_django
      # - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=hello_django_dev
      - MYSQL_USER=hello_django
      - MYSQL_PASSWORD=hello_django

volumes:
  mariadb_data:
